runs:
  using: "composite"
  steps:
    - name: Run tests
      run: |
          cd ${GITHUB_WORKSPACE}/build
          ./unit_tests/test_SVD
          ./unit_tests/test_Vector
          ./unit_tests/test_Matrix
          ./unit_tests/test_DEIM
          ./unit_tests/test_GNAT
          ./unit_tests/test_QDEIM
          ./unit_tests/test_S_OPT
          mpirun -n 4 --oversubscribe unit_tests/test_S_OPT
          ./unit_tests/test_IncrementalSVD
          ./unit_tests/test_RandomizedSVD
          mpirun -n 3 --oversubscribe unit_tests/test_RandomizedSVD
          ./unit_tests/test_DMD
          mpirun -n 3 --oversubscribe unit_tests/test_DMD
          ./unit_tests/test_GreedyCustomSampler
          mpirun -n 3 --oversubscribe unit_tests/test_GreedyCustomSampler
          cd {GITHUB_WORKSPACE}/regression_tests
          ./{GITHUB_WORKSPACE}/regression_tests/run_regression_tests.sh

          
         

      shell: bash
