runs:
  using: "composite"
  steps:
    - name: Run tests
      run: |
          cd ${GITHUB_WORKSPACE}/build
          ./tests/test_SVD
          ./tests/test_Vector
          ./tests/test_Matrix
          ./tests/test_DEIM
          ./tests/test_GNAT
          ./tests/test_QDEIM
          ./tests/test_IncrementalSVD
          ./tests/test_RandomizedSVD
          mpirun -n 3 --oversubscribe tests/test_RandomizedSVD
          ./tests/test_DMD
          mpirun -n 3 --oversubscribe tests/test_DMD
          ./tests/test_GreedyCustomSampler
          mpirun -n 3 --oversubscribe tests/test_GreedyCustomSampler
           cd ${GITHUB_WORKSPACE}
          ./regression_tests/run_regression_tests.sh
          echo "Printing dg_advection log"
          cat regression_tests/results/dg_advection.log
          echo "Printing dg_euler log"
          cat regession_tests/results/dg_euler.log
          echo "Printing parametric_heat_conduction log"
          cat regression_tests/results/parametric_heat_conduction.log
         

      shell: bash
