runs:
  using: "composite"
  steps:
    - name: Run tests
      run: |
          cd ${GITHUB_WORKSPACE}/build/examples/prom
          poisson_global_rom -offline -f 1.0 -id 0
          poisson_global_rom -offline -f 1.1 -id 1
          poisson_global_rom -offline -f 1.2 -id 2
          poisson_global_rom -merge -ns 3
          poisson_global_rom -online -f 1.15

      shell: bash
