name: CI
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux dependencies
        run: |
            sudo apt-get install libmpich-dev libblas-dev liblapack-dev libscalapack-mpi-dev libhdf5-serial-dev
      - name: Check out libROM
        uses: actions/checkout@v2
      - uses: ./.github/workflows/checkout_repo
      - name: Build libROM
        run: |
            mkdir ${GITHUB_WORKSPACE}/build
            export CC=mpicc
            export CXX=mpicxx
            scripts/setup.sh
            cd ${GITHUB_WORKSPACE}/build
            cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_MFEM=On ..
            make
            cmake -DCMAKE_BUILD_TYPE=Optimized -DUSE_MFEM=On ..
            make
      - uses: ./.github/workflows/run_tests
      - name: Build libROM Baseline # Defaults to the 'master' branch
          run: |

            mkdir ${GITHUB_WORKSPACE}/dependencies/build
            cd ${GITHUB_WORKSPACE}/dependencies/build
            git clone 
            export CC=mpicc
            export CXX=mpicxx
            git clone https://github.com/LLNL/libROM.git
            scripts/setup.sh
            cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_MFEM=On ..
            make
            cmake -DCMAKE_BUILD_TYPE=Optimized -DUSE_MFEM=On ..
            make
      - uses: ./.github/workflows/run_tests
          
  mac:
    runs-on: macos-latest
    steps:
      - name: Install Mac dependencies
        run: |
            brew install open-mpi
            brew install openblas
            brew install lapack
            brew install scalapack
            brew install hdf5
      - name: Check out libROM
        uses: actions/checkout@v2
      - uses: ./.github/workflows/checkout_repo
      - name: Build libROM
        run: |
            mkdir ${GITHUB_WORKSPACE}/build
            export FC=/usr/local/bin/gfortran-10
            scripts/setup.sh
            cd ${GITHUB_WORKSPACE}/build
            cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_MFEM=On ..
            make
            cmake -DCMAKE_BUILD_TYPE=Optimized -DUSE_MFEM=On ..
            make
      - uses: ./.github/workflows/run_tests
      name: Build libROM Baseline
        run: |
            mkdir ${GITHUB_WORKSPACE}/dependencies/build
            export FC=/usr/local/bin/gfortran-10
            cd ${GITHUB_WORKSPACE}/dependencies/build
            git clone https://github.com/LLNL/libROM.git
            scripts/setup.sh
            cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_MFEM=On ..
            make
            cmake -DCMAKE_BUILD_TYPE=Optimized -DUSE_MFEM=On ..
            make
      - uses: ./.github/workflows/run_tests
